const BAD_REQUEST  = 400;
const UNAUTHORIZED_USER = 401;
const FORBIDDEN_ACCESS = 403;
const NOT_FOUND = 403;
const STATUS_OK = 200;
const STATUS_CREATED  = 201;
const INTERNAL_SERVER_ERROR  = 500;

module.exports = {BAD_REQUEST,UNAUTHORIZED_USER, STATUS_OK,STATUS_CREATED, FORBIDDEN_ACCESS, INTERNAL_SERVER_ERROR, NOT_FOUND};